"""Add FK

Revision ID: 26c635138bee
Revises: 6c80a150c8bb
Create Date: 2023-09-03 19:55:10.560054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c635138bee'
down_revision: Union[str, None] = '6c80a150c8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'])
    op.add_column('rooms', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'hotel_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'room_id')
    op.drop_column('bookings', 'user_id')
    # ### end Alembic commands ###
